homepage:
    path:     /
    defaults: { _controller: SVEleveBundle:Pupil:home }

sv_eleve:
    resource: "@SVEleveBundle/Resources/config/routing.yml"
    prefix:   /pupil

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin