<?php

namespace SV\EleveBundle\Repository;

/**
 * AbsencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsencesRepository extends \Doctrine\ORM\EntityRepository
{
}
