<?php

namespace SV\EleveBundle\Repository;
use SV\EleveBundle\Entity\ElevesClasses;
/**
 * ClassesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByEleveClasse(ElevesClasses $elevesClasses)
    {
        $qb = $this->_em->createQueryBuilder('c');
        $qb
            ->where('c.eleveclasses = :id')
            ->setParameter('id', $elevesClasses);

        $q = $qb->getQuery();
        $result = $q->getResult();

        return $result;
    }
}
