<?php

namespace SV\EleveBundle\Repository;

/**
 * CollegesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollegesRepository extends \Doctrine\ORM\EntityRepository
{
}
