<?php

namespace SV\EleveBundle\Repository;

/**
 * DevoirsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevoirsRepository extends \Doctrine\ORM\EntityRepository
{
}
