<?php

namespace SV\EleveBundle\Repository;

/**
 * DisciplinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinesRepository extends \Doctrine\ORM\EntityRepository
{
}
