<?php

namespace SV\EleveBundle\Repository;

/**
 * ElevesClassesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElevesClassesRepository extends \Doctrine\ORM\EntityRepository
{
}
