<?php

namespace SV\EleveBundle\Repository;

/**
 * FinancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancesRepository extends \Doctrine\ORM\EntityRepository
{
}
