<?php

namespace SV\EleveBundle\Repository;

/**
 * NiveauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauxRepository extends \Doctrine\ORM\EntityRepository
{
}
