<?php

namespace SV\EleveBundle\Repository;

/**
 * PlanningsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningsRepository extends \Doctrine\ORM\EntityRepository
{
}
