<?php

namespace SV\EleveBundle\Repository;

/**
 * ProgrammesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammesRepository extends \Doctrine\ORM\EntityRepository
{
}
